services:
  reverse-proxy:
    image: docker.io/library/traefik:v3.0
    command:
      # TODO SSL with HTTP-01
      - --api.insecure=true
      - --providers.docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  example-service:
    image: example-service
    labels:
      - traefik.http.routers.example-service.rule=Host(`example.127-0-0-1.nip.io`)
      - traefik.http.services.example-service.loadbalancer.server.port=8080
