#!/bin/sh

set -eu

cd ..

service="$(basename "${PWD}")"

docker run \
    --volume /var/run/docker.sock:/var/run/docker.sock \
    --volume "${PWD}:/workspace" \
    --workdir /workspace \
    buildpacksio/pack build --builder=heroku/builder:22 "${service}"

cd ../../

docker compose up --detach --remove-orphans
