#!/bin/sh

set -eu

cd ..

service="$(basename "${PWD}")"

if [ -f ./Dockerfile ]; then
    docker build --tag "${service}" .
else
    docker run \
        --volume /var/run/docker.sock:/var/run/docker.sock \
        --volume "${PWD}:/workspace" \
        --workdir /workspace \
        buildpacksio/pack build --builder=heroku/builder:22 "${service}"
fi

cd ../../

docker compose up --detach --remove-orphans
